### ISSUE TITLE
What is the recommended way of using these charts in an existing qt-application?

### ISSUE THREAD

**Issue by FDePourcq** [colinw7/CQCharts#4]
Hi, 
I managed to compile cqcharts and its test-binary. (To those who might be interested, the compilation required these repositories: CArgs  CConfig  CCsv  CFile  CFileUtil  CFont  CGlob  CImageLib  CJson  CMath  cmd  COS  CQBaseModel  CQCharts  CQColors  CQCustomCombo  CQDividedArea  CQModelView  CQPerfMonitor  CQPropertyView  CQUtil  CReadLine  CRegExp  CStrUtil  CTsv  CUtil  CXML ) 

Commands like "colinw7_all/CQCharts/data (master) $ export PATH=${PATH}:. &&  ./charts.sh sankey_energy.tcl" work fine, got a nice sankey.

Now I try to use that sankey-widget in a unrelated qt5/c++ app  with custom runtime data.

What I got so far, starting from a basic qt-example [Qt-CMake-HelloWorld](https://github.com/jasondegraw/Qt-CMake-HelloWorld.git) , in mainwindow.cpp: 

```
#include "mainwindow.h"
#include "ui_mainwindow.h"


#include <iostream>

#include <CQCharts.h>
#include <CQChartsSankeyPlot.h>
#include <CQCsvModel.h>
#include <CQChartsPlotType.h>
#include <CQChartsModelData.h>
#include <CQChartsLoader.h>
#include <CQChartsInputData.h>
#include <CQChartsFile.h>

MainWindow::MainWindow(QWidget *parent) :
        QMainWindow(parent) //,    ui(new Ui::MainWindow)
{

    CQCharts *charts = new CQCharts();

    charts->init();

    auto *view = charts->createView(); //charts->currentView();// charts->createView();

    CQChartsInputData inputData;

//    inputData.commentHeader     = this->isCommentHeader();
    inputData.firstLineHeader   = true;// this->isFirstLineHeader();
//    inputData.firstColumnHeader = this->isFirstColumnHeader();
//    inputData.numRows           = this->numRows();
//    inputData.filter            = this->filterStr();


    CQChartsLoader loader(charts);

    bool hierarchical = false;
    CQChartsFile file(charts,QString("/home/donf/src_other/colinw7_all/CQCharts/data/data/sankey_energy.csv") );
    QAbstractItemModel* model =  loader.loadFile(file, CQChartsFileType::CSV ,  inputData  , hierarchical );

    CQChartsPlot::ModelP* modelp = new CQChartsPlot::ModelP(model);

    auto *modelData = charts->initModelData(*modelp);

    charts->setModelFileName(modelData, file.resolve());

    auto *modelData2 = charts->currentModelData();
    assert(modelData2);

    CQChartsSankeyPlotType plottype;
    std::cerr << plottype.description().toStdString().c_str() << std::endl;
    std::cerr << plottype.name().toStdString().c_str() << std::endl;

    auto plot = plottype.create(view, *modelp);
    plot->setModel(*modelp);
    assert(plot->getModelData());
    plot->init();


    view->setCurrentPlot(plot);
    //view->initOverlayAxes();

    this->setCentralWidget(view);
}

MainWindow::~MainWindow() {
    //delete ui;
}

void MainWindow::on_actionExit_triggered() {
    this->close();
}
```

To my surprise this gave me a html-page with the full power of the cqcharts-gui instead of a sankey-widget.

So I wonder what would be the correct cleanest way to approach this. Is there for example a way to get the widget without instantiating the all-encompassing cqcharts-object? 

Greetings, nice work btw, impressive.

Ps:  here is the modified cmake-file too:
[CMakeLists.txt](https://github.com/colinw7/CQCharts/files/7186289/CMakeLists.txt)

**Comment by FDePourcq** [comment]
Hi, 
I managed to compile cqcharts and its test-binary. (To those who might be interested, the compilation required these repositories: CArgs  CConfig  CCsv  CFile  CFileUtil  CFont  CGlob  CImageLib  CJson  CMath  cmd  COS  CQBaseModel  CQCharts  CQColors  CQCustomCombo  CQDividedArea  CQModelView  CQPerfMonitor  CQPropertyView  CQUtil  CReadLine  CRegExp  CStrUtil  CTsv  CUtil  CXML ) 

Commands like "colinw7_all/CQCharts/data (master) $ export PATH=${PATH}:. &&  ./charts.sh sankey_energy.tcl" work fine, got a nice sankey.

Now I try to use that sankey-widget in a unrelated qt5/c++ app  with custom runtime data.

What I got so far, starting from a basic qt-example [Qt-CMake-HelloWorld](https://github.com/jasondegraw/Qt-CMake-HelloWorld.git) , in mainwindow.cpp: 

`#include "mainwindow.h"
#include "ui_mainwindow.h"


#include <iostream>

#include <CQCharts.h>
#include <CQChartsSankeyPlot.h>
#include <CQCsvModel.h>
#include <CQChartsPlotType.h>
#include <CQChartsModelData.h>
#include <CQChartsLoader.h>
#include <CQChartsInputData.h>
#include <CQChartsFile.h>

MainWindow::MainWindow(QWidget *parent) :
        QMainWindow(parent) //,    ui(new Ui::MainWindow)
{

    CQCharts *charts = new CQCharts();

    charts->init();

    auto *view = charts->createView(); //charts->currentView();// charts->createView();

    CQChartsInputData inputData;

//    inputData.commentHeader     = this->isCommentHeader();
    inputData.firstLineHeader   = true;// this->isFirstLineHeader();
//    inputData.firstColumnHeader = this->isFirstColumnHeader();
//    inputData.numRows           = this->numRows();
//    inputData.filter            = this->filterStr();


    CQChartsLoader loader(charts);

    bool hierarchical = false;
    CQChartsFile file(charts,QString("/home/donf/src_other/colinw7_all/CQCharts/data/data/sankey_energy.csv") );
    QAbstractItemModel* model =  loader.loadFile(file, CQChartsFileType::CSV ,  inputData  , hierarchical );

    CQChartsPlot::ModelP* modelp = new CQChartsPlot::ModelP(model);

    auto *modelData = charts->initModelData(*modelp);

    charts->setModelFileName(modelData, file.resolve());

    auto *modelData2 = charts->currentModelData();
    assert(modelData2);

    CQChartsSankeyPlotType plottype;
    std::cerr << plottype.description().toStdString().c_str() << std::endl;
    std::cerr << plottype.name().toStdString().c_str() << std::endl;

    auto plot = plottype.create(view, *modelp);
    plot->setModel(*modelp);
    assert(plot->getModelData());
    plot->init();


    view->setCurrentPlot(plot);
    //view->initOverlayAxes();

    this->setCentralWidget(view);
}

MainWindow::~MainWindow() {
    //delete ui;
}

void MainWindow::on_actionExit_triggered() {
    this->close();
}
`

To my surprise this gave me a html-page with the full power of the cqcharts-gui instead of a sankey-widget.

So I wonder what would be the correct cleanest way to approach this. Is there for example a way to get the widget without instantiating the all-encompassing cqcharts-object? 

Greetings, nice work btw, impressive.

**Comment by colinw7** [comment]
Adding a charts view to an existing Qt Application is not trivial but it
looks you are very close in your example. Just adding the EkChartsView
widget is good enough to start with but customization and manipulation of
the view requires hooks into any existing infrastructure for the
QMainWindow dock areas (settings), toolbars (mouse tools) and status bar
(selection status, mouse position) you can see some of this in the
EkChartsWindow class but it usually depends on the exact structure of the
existing application.

I updated your example code and added it in examples/sankey_view so you can
progress further. I think the only thing you were missing was setting the
columns for the plot so it knows what data from the model to use.

**Comment by FDePourcq** [comment]
Nice!
I also got rid of the  CQChartsInputData/CQChartsLoader/CQCsvModel by using an instance of this as pmodel:

```
struct Custom2DData : CQDataModel {
    Custom2DData() {
        hheader_.push_back("from/to");
        hheader_.push_back("value");
        data_.push_back(std::vector<QVariant> { "Coal/Solid" ,75.571} );
        data_.push_back(std::vector<QVariant> { "Solid/Industry" , 46.477} );
    };
};
```

I guess all the requirements are met for using it now as a widget :) The qt-thread will have to update the model to avoid multithreading-issues but that is fine. 

Thanks!
