### ISSUE TITLE
sankey node depth calculation issue

### ISSUE THREAD

**Issue by FDePourcq** [colinw7/CQCharts#5]
Hi,
I noted that whenever there are multiple paths between the same nodes in the sankey-graph that some nodes get positioned on top of oneanother, resulting in a flow within a single column.

The `calcDestDepth`-function in `CQChartsSankeyPlot.cpp` seems to be the culprit. When it takes a short path to the destination, it will subsequently fail to recognize the longer paths to the same destination because of the visited-check.
This seems to solve it?:

```
 int
 CQChartsSankeyPlotNode::
 calcDestDepth(NodeSet &visited) const
 {
   if (destDepth_ >= 0)
     return destDepth_;
 
   auto *th = const_cast<CQChartsSankeyPlotNode *>(this);
 
   if (destEdges_.empty()) {
     th->destDepth_ = 0;
   }
   else {
     int depth = 0;
 
     for (const auto &edge : destEdges_) {
       if (edge->isSelf()) continue;
 
       auto *node = edge->destNode();
 
       auto p = visited.find(node);
 
       if (p == visited.end()) {
         visited.insert(node);
 
         depth = std::max(depth, node->calcDestDepth(visited));
+      }else{
+       std::cerr << "calcDestDepth " << "depth: " <<  depth <<  "  node->depth(): " << node->depth() << " destdepth " << node->destDepth_ << std::endl;
+        depth = std::max(depth, node->destDepth_ );
       }
     }
 
     th->destDepth_ = depth + 1;
   }
 
   return destDepth_;
 }

```
Similar issue with `calcSrcDepth`, though I havent executed that.

**Comment by colinw7** [comment]
Interesting, do you have any data to demonstrate this. I'd like to
reproduce the issue and try your fix.

**Comment by FDePourcq** [comment]
Eg  a simple path from 0.5 -> 1 -> 10 -> 11  with and alternative longer path between 1 and 10 via 5. The 5 ends up on the 1.

```#source/target,amount                                                                                                                                                                                                                                                                                                                                                                      
0.5/1,1                                                                                                                                                                                                                                                                                                                                                                                    
1/10,1                                                                                                                                                                                                                                                                                                                                                                                     
10/11,1                                                                                                                                                                                                                                                                                                                                                                                    
1/5,1                                                                                                                                                                                                                                                                                                                                                                                      
5/10,1```

![overlappingnodes](https://user-images.githubusercontent.com/17044338/134466118-accbff93-3d45-4eec-8626-8e5b71b16ab9.jpg)

**Comment by FDePourcq** [comment]
Btw, I'm also interested in a proper way to disable
```
    else if (destDepth == 0)
      pos = graph_->maxNodeDepth();
```
in `CQChartsSankeyPlot::calcPos(Node *node) const` .
That line causes the final destination-nodes to be placed at the outer-right column and that causes the streams to be unnecessary long. That might make sense for the energy-chart but often it doesnt.

**Comment by colinw7** [comment]
Hi,
  I made some adjustments to to calDestDepth code as you suggested and
added a new option 'alignFirstLast' to set depth of nodes with zero
source/dest connections to the max depth of the next/prev connected nodes
which hopefully does what you want.
  Note: if you have better depth values for your nodes you can use the
depth column to set them in your model.

**Comment by FDePourcq** [comment]
Thanks!

**Comment by KTL** [comment]
Hallo again, this exact same issue is still around (the incorrect srcDepth calculation) :) :D 
And here is another way of fixing it (slightly less efficient than my previous solution): 
```  int
 CQChartsSankeyPlotNode::
 calcSrcDepth(NodeSet &visited) const
 {
   if (srcDepth_ >= 0)
     return srcDepth_;
 
   auto *th = const_cast<CQChartsSankeyPlotNode *>(this);
 
   if (srcEdges_.empty()) {
     th->srcDepth_ = 0;
   }
   else {
     int depth = 0;
 
     for (const auto &edge : srcEdges_) {
       if (edge->isSelf()) continue;
 
       auto *node = edge->srcNode();
 
       auto p = visited.find(node);
 
       if (p == visited.end()) {
-        visited.insert(node);
-
-        depth = std::max(depth, node->calcSrcDepth(visited));
-      }
-      else {
-        depth = std::max(depth, int(visited.size() - 1));
-      //depth = std::max(depth, node->srcDepth());
+        auto visited2 = visited;
+        visited2.insert(node);
+        depth = std::max(depth, node->calcSrcDepth(visited2));
       }
     }
 
     th->srcDepth_ = depth + 1;
   }
 
   return srcDepth_;
 }

```
Basically, the intent is to find the longest path from the current Node to a source. But the mechanism against infinite loops (the visited-set)  in the current implementation is just not correctly implemented. Because the visited-set is reused during the iteration over every possible incoming path ... it will only grow and sabotage subsequent good candidates with longer paths...
So either a fresh copy should be used for checking every incoming edge  (`auto visited2 = visited`) 
or we reason "aha this node has been visited already, its srcDepth will already have been set, let's use that value.".  

The other thing, with `calcPos(Node *node)`. I'm still not entirely getting your firstlast-solution, the thing i actually tried to get years ago and still do  looks more like 
```int
CQChartsSankeyPlot::
calcPos(Node *node) const
{
    auto ret = node->srcDepth();
    node->setPos(ret);
    return ret;
```
It has to do with the `align == SRC`, where I try to get every node pushed to the SRC as much as possible, including the nodes at DEST. Maybe the clean solution is to have additional alignment options besides SRC, not sure what to call it, `SRC_ALL` ? 

(Yes I could probably use the depth-column as you proposed, but this would be silly to reimplement at my side considering it is a very basic feature.)

**Comment by FDePourcq** [comment]
Hallo again, this exact same issue is still around (the incorrect srcDepth calculation) :) :D
And here is another way of fixing it (slightly less efficient than my previous solution):
```
 int
 CQChartsSankeyPlotNode::
 calcSrcDepth(NodeSet &visited) const
 {
   if (srcDepth_ >= 0)
     return srcDepth_;
 
   auto *th = const_cast<CQChartsSankeyPlotNode *>(this);
 
   if (srcEdges_.empty()) {
     th->srcDepth_ = 0;
   }
   else {
     int depth = 0;
 
     for (const auto &edge : srcEdges_) {
       if (edge->isSelf()) continue;
 
       auto *node = edge->srcNode();
 
       auto p = visited.find(node);
 
       if (p == visited.end()) {
-        visited.insert(node);
-
-        depth = std::max(depth, node->calcSrcDepth(visited));
-      }
-      else {
-        depth = std::max(depth, int(visited.size() - 1));
-      //depth = std::max(depth, node->srcDepth());
+        auto visited2 = visited;
+        visited2.insert(node);
+        depth = std::max(depth, node->calcSrcDepth(visited2));
       }
     }
 
     th->srcDepth_ = depth + 1;
   }
 
   return srcDepth_;
 }

```
Basically, the intent is to find the longest path from the current Node to a source. But the mechanism against infinite loops (the visited-set) in the current implementation is just not correctly implemented. Because the visited-set is reused during the iteration over every possible incoming path ... it will only grow and sabotage subsequent good candidates with longer paths...
So either a fresh copy should be used for checking every incoming edge (auto visited2 = visited)
or we reason "aha this node has been visited already, its srcDepth will already have been set, let's use that value.".

The other thing, with calcPos(Node *node). I'm still not entirely getting your firstlast-solution, the thing i actually tried to get years ago and still do looks more like
```
CQChartsSankeyPlot::
calcPos(Node *node) const
{
    auto ret = node->srcDepth();
    node->setPos(ret);
    return ret;
```
It has to do with the align == SRC, where I try to get every node pushed to the SRC as much as possible, including the nodes at DEST. Maybe the clean solution is to have additional alignment options besides SRC, not sure what to call it, SRC_ALL ?

(Yes I could probably use the depth-column as you proposed, but this would be silly to reimplement at my side considering it is a very basic feature.)

**Comment by colinw7** [comment]
Welcome back and thanks for the new code.

I tested it locally and didn't see any issues so I made it default but left the old code as I can vaguely remember problems with our last change to this.

I also added the SRC_ALL and DEST_ALL alignment modes as suggested (not a great name but suffices for now).

Let me know if you see any issues.
