### ISSUE TITLE
Header files CQDataModel.h, CQBaseModelTypes.h, CQUtilMeta.h, tcl.h and QregExp files are missing

### ISSUE THREAD

**Issue by SusannaDiV** [colinw7/CQCharts#6]
Hi,
I just pulled you code and tried to compile it using Qt Creator 6.0.0 - but I get those missing files error during building.
Do you happen to still have them, or did I compile the project file wrong?

**Comment by colinw7** [comment]
This project has a large number of dependencies on code in other projects. See doc/DEPENDS.md for details on how to which other projects need to be added to the source tree to build.

**Comment by SusannaDiV** [comment]
Thank you so much!

**Comment by SusannaDiV** [comment]
After installing all the dependencies in the CQCharts.pro INCLUDEPATH variable, I still get the "No such file or directory" for the files present in the title, while all the other project files from the other repos are working (after changing the configuration to c++17) - did I happen to build the project wrong?

**Comment by colinw7** [comment]
CQDataModel.h and CQBaseModelTypes.h are in CQBaseModel repository. CQUtilMeta.h is in CQUtil repository.
QRegExp is from Qt (using Qt 5.12) and tcl.h is from tcl8.6-dev apt package.

**Comment by colinw7** [comment]
FYI, I added a build script in scripts/build.sh which can be run to download all dependent packages and build CQCharts library and executable. Still needs work but may help. Details on how to use in file and in doc/DEPENDS/md

**Comment by SusannaDiV** [comment]
Thank you so much - I have no problems with it now, altough I'm still searching what dependency I missed first!
