### ISSUE TITLE
Does the work still support Graphviz plot?

### ISSUE THREAD

**Issue by Jiraruko** [colinw7/CQCharts#7]
Hi,
I found some image examples using Graphviz library but when I try to run $./charts.sh (Any Graphviz tcl script), the screen of CQChartTests gui says "NO DATA". 

Am I missing something?

BTW, your work is amazing.
Thank you in advance.
J.

**Comment by colinw7** [comment]
could you give more details on what data/tcl you are using to generate the
graphviz plot ?

I tested with example data from data directory
CQCharts/data/graphviz/graphviz_energy.tcl and apart from some node shape
drawing issues which I fixed it works as expected.

**Comment by jiratiwat-personal** [comment]
Thank you for your prompt reply and support.
I used the command "charts.sh" command and try using the tcl file inside the directory "CQCharts/data/graphviz/" as an argument. 
However, none of them produce results as for the Sankey graph or other types available.

FYI,
My system is Ubuntu 22, Qt5.15. 
CQCharts was built using the experimental build script you provide. 

Please let me know if I might have forgotten something.
Thank you in advance.

**Comment by jiratiwat-personal** [comment]
Please see the attached text file for the built output history
[built.txt](https://github.com/colinw7/CQCharts/files/11768970/built.txt)

I also edit charts.sh at line 161 to set the "exe" variable to my current CQChartsTest directory. Hope this is not a problem.

The command I used is 
./charts.sh graphviz/graphviz_energy.tcl
and the result is below
![image](https://github.com/colinw7/CQCharts/assets/103764858/04ce9873-89be-46fe-91eb-2bc16a3c1256)

Thank you in advance.

**Comment by colinw7** [comment]
The only way I can duplicate this issue is if it can't find the graphviz
executable for the placement engine. In this case an error should be
printed on the console e.g.

Command failed or timed out : /fred/fdp -Txdot /tmp/lbvNBt.gv >
/tmp/nyBwuK.xdot

Do you have graphviz installed ? You can set the location (directory) for
the graphviz executables using

setenv CQCHARTS_DOT_PATH <dir>

by default it it /bin e.g. for me

> which fdp
/bin/fdp

**Comment by jiratiwat-personal** [comment]
Your assumption is very precise!
I installed the latest GraphViz library from the official website to the default directory and this works fine.
I wondered if the look of the plot is expected to be in the picture below, considering the undergoing development.
![image](https://github.com/colinw7/CQCharts/assets/103764858/9ea02ecb-8092-47c2-af57-957ac5a30354)


Thank you for your support!
