### ISSUE TITLE
Compilation of the examples/sankey_view issue

### ISSUE THREAD

**Issue by jiratiwat-personal** [colinw7/CQCharts#8]
HI,
I tried to compile the example code in examples/sankey_view but got an issue. 
initially, I configured the .pro file a bit further to get it built on my system as shown below.
[pro.txt](https://github.com/colinw7/CQCharts/files/11786136/pro.txt)
After the modification, I was able to build the project. 
However, when I run it, it throws an error at the line "auto *modelData = charts_->initModelData(modelp);".
This is the output error on my console

10:44:46: Starting /home/ku/git/99_GitHub/CQCharts/build2/CQCharts/examples/build-CQChartsSankeyView-Desktop_Qt_5_15_14_GCC_64bit-Debug/CQChartsSankeyView...
Ubuntu,11,-1,5,50,0,0,0,0,0 mismatch
Ubuntu,11,-1,5,50,0,0,0,0,0 mismatch
Failed to load ''
CQChartsSankeyView: CQCharts.cpp:1538: int CQCharts::addModelData(CQCharts::ModelP&): Assertion `rc' failed.
10:44:46: /home/ku/git/99_GitHub/CQCharts/build2/CQCharts/examples/build-CQChartsSankeyView-Desktop_Qt_5_15_14_GCC_64bit-Debug/CQChartsSankeyView crashed.

Please suggest what am I missing.
Thank you in advance!

**Comment by jiratiwat-personal** [comment]
Hi, 
I figured out that I forget to change the file directory when declaring CQChartsFile.
The project can generate the plot successfully.

Best.

**Comment by colinw7** [comment]
The assert is because it can't find the sankey_energy.csv file in the
current directory.

I added extra error checking so it doesn't crash for this issue.
